kernel: Fix cake patch for kernel 4.19.138
This fixes the following build problem with cake:
net/sched/act_ctinfo.c: In function 'tcf_ctinfo_act':
net/sched/act_ctinfo.c:99:6: error: implicit declaration of function 'tc_skb_protocol'; did you mean 'skb_protocol'? [-Werror=implicit-function-declaration]
  if (tc_skb_protocol(skb) == htons(ETH_P_IP)) {
      ^~~~~~~~~~~~~~~
      skb_protocol
  CC [M]  net/sched/sch_hfsc.o

Fixes: fdac05b7416b ("kernel: Update kernel 4.19 to version 4.19.138")
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>