usbreset: Add missing header
Fixes undefined reference to strtoul

Signed-off-by: Rosen Penev <rosenp@gmail.com>
(cherry picked from commit 653e05d27f13fee2ab925031c5162ddb34b755f0)